# Azure Pipelines YAML for building and publishing Docker image and Helm chart
# This pipeline builds the Dockerfile, pushes it to Azure Container Registry (ACR),
# packages the Helm chart, and pushes the chart as an OCI artifact to ACR

trigger:
  branches:
    include:
      - master
      - main
  paths:
    exclude:
      - README.md
      - LICENSE
      - examples/**
      - .gitignore

pr:
  branches:
    include:
      - master
      - main

variables:
  # Set these to your Azure Container Registry details
  ACR_NAME: fanfindadmin
  IMAGE_NAME: azure-devops-agent
  IMAGE_TAG: $(Build.BuildId)
  CHART_VERSION: $(Build.BuildNumber)
  # Add additional tags for versioning
  IS_MAIN_BRANCH: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

pool: 
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndPush
    displayName: 'Build Docker Image and Helm Chart'
    steps:
      - template: .azuredevops/templates/build-and-push.yml
        parameters:
          acrName: $(ACR_NAME)
          imageName: $(IMAGE_NAME)
          imageTag: $(IMAGE_TAG)
          azureSubscription: 'Azure'
          chartPath: './chart'
          runVulnerabilityScan: true
